clone_depth: 1

#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    matrix:
        - MINGW_VERSION: mingw32
          ARCH: i686
          ARCH_BIT: 32
          
        - MINGW_VERSION: mingw64
          ARCH: x86_64
          ARCH_BIT: 64
          
matrix:
    fast_finish: true

install:
    # Install Inno Setup
    - choco install InnoSetup

build_script:
    - C:\msys64\usr\bin\bash build.sh
    - mkdir C:\%DEBUG_FOLDER%
    - mv C:\%DEST_FOLDER%\Scopy.exe.sym C:\%DEBUG_FOLDER%
    - mv C:\%DEST_FOLDER%\.debug C:\%DEBUG_FOLDER%

    - 7z a "c:\scopy-%ARCH_BIT%bit.zip" c:\%DEST_FOLDER%
    - appveyor PushArtifact c:\scopy-%ARCH_BIT%bit.zip
    - 7z a "C:\debug-%ARCH_BIT%bit.zip" c:\%DEBUG_FOLDER%
    - appveyor PushArtifact C:\debug-%ARCH_BIT%bit.zip
    
    # Build the installer
    - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
    - ISCC /Q C:\%BUILD_FOLDER%\scopy-%ARCH_BIT%.iss
    - appveyor PushArtifact C:\scopy-%ARCH_BIT%-setup.exe
#on_finish:
#      - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
